"""add ghl_tasks table

Revision ID: 081c6bfb1e77
Revises: 49ccc54b9269
Create Date: 2026-02-19 03:41:33.980360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081c6bfb1e77'
down_revision = '49ccc54b9269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ghl_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ghl_task_id', sa.String(length=255), nullable=False),
    sa.Column('ghl_contact_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('contact_first_name', sa.String(length=100), nullable=True),
    sa.Column('contact_last_name', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ghl_task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ghl_tasks')
    # ### end Alembic commands ###
