"""add new field for post Type

Revision ID: 0d206e4eb3c0
Revises: 541e1335dac2
Create Date: 2025-10-20 02:29:05.450993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d206e4eb3c0'
down_revision = '541e1335dac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_visibility', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_posts', schema=None) as batch_op:
        batch_op.drop_column('privacy_visibility')

    # ### end Alembic commands ###
