"""Add parent_comment_id to facebook_comments for reply support

Revision ID: 3009214a5c2a
Revises: cc618a051c3b
Create Date: 2025-10-20 04:06:00.002656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3009214a5c2a'
down_revision = 'cc618a051c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'facebook_comments', ['parent_comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_comment_id')

    # ### end Alembic commands ###
