"""add scheduled_at to call_logs

Revision ID: 3d98b1cbd691
Revises: a7b0347981e6
Create Date: 2026-03-13 22:04:32.293194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d98b1cbd691'
down_revision = 'a7b0347981e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_column('scheduled_at')

    # ### end Alembic commands ###
