"""Add is_agency column to ghl_tokens

Revision ID: 49ccc54b9269
Revises: fd180a5b7169
Create Date: 2026-02-04 03:31:06.237830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ccc54b9269'
down_revision = 'fd180a5b7169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ghl_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_agency', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ghl_tokens', schema=None) as batch_op:
        batch_op.drop_column('is_agency')

    # ### end Alembic commands ###
