"""add frozen_at frozen_expires_at to phone_numbers

Revision ID: a7b0347981e6
Revises: a89e71cb2d17
Create Date: 2026-03-11 19:12:43.286860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b0347981e6'
down_revision = 'a89e71cb2d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frozen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('frozen_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.drop_column('frozen_expires_at')
        batch_op.drop_column('frozen_at')

    # ### end Alembic commands ###
