"""add user_call_configs call_analytics display_name lead_context template_used

Revision ID: a89e71cb2d17
Revises: 6e4a3f2a06ea
Create Date: 2026-03-06 14:16:45.759367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89e71cb2d17'
down_revision = '6e4a3f2a06ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_call_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=True),
    sa.Column('default_language', sa.String(length=10), nullable=True),
    sa.Column('fallback_language', sa.String(length=10), nullable=True),
    sa.Column('language_overrides', sa.Text(), nullable=True),
    sa.Column('greeting_template', sa.Text(), nullable=True),
    sa.Column('greeting_presets', sa.Text(), nullable=True),
    sa.Column('system_prompt_base', sa.Text(), nullable=True),
    sa.Column('voice_provider', sa.String(length=50), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('call_window_start', sa.Time(), nullable=True),
    sa.Column('call_window_end', sa.Time(), nullable=True),
    sa.Column('call_window_days', sa.Text(), nullable=True),
    sa.Column('call_window_timezone', sa.String(length=50), nullable=True),
    sa.Column('active_template', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('call_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('interest_level', sa.Integer(), nullable=True),
    sa.Column('objections', sa.Text(), nullable=True),
    sa.Column('success_evaluation', sa.String(length=20), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_log_id')
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_context', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('template_used', sa.String(length=100), nullable=True))

    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_column('template_used')
        batch_op.drop_column('lead_context')

    op.drop_table('call_analytics')
    op.drop_table('user_call_configs')
    # ### end Alembic commands ###
