"""add sms_logs table

Revision ID: ab59919da30d
Revises: 3d98b1cbd691
Create Date: 2026-03-20 02:45:36.022629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab59919da30d'
down_revision = '3d98b1cbd691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('twilio_sid', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=10), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_valid_number', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_logs_twilio_sid'), ['twilio_sid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_logs_twilio_sid'))

    op.drop_table('sms_logs')
    # ### end Alembic commands ###
