"""add new field for comments Table

Revision ID: cc618a051c3b
Revises: 0d206e4eb3c0
Create Date: 2025-10-20 03:36:23.912583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc618a051c3b'
down_revision = '0d206e4eb3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_date', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('post_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('has_liked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=255), nullable=True))
        batch_op.drop_column('created_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('language')
        batch_op.drop_column('has_liked')
        batch_op.drop_column('post_url')
        batch_op.drop_column('comment_date')

    # ### end Alembic commands ###
