"""Added Location Id in User's Table

Revision ID: dee34f827197
Revises: e3658856fb82
Create Date: 2025-10-30 02:29:33.473518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee34f827197'
down_revision = 'e3658856fb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ghl_location_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ghl_location_id')

    # ### end Alembic commands ###
