"""Added Some More fields in comments table

Revision ID: e3658856fb82
Revises: 3009214a5c2a
Create Date: 2025-10-24 02:57:12.329396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3658856fb82'
down_revision = '3009214a5c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('self_comment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('ai_reply')
        batch_op.drop_column('self_comment')

    # ### end Alembic commands ###
