"""Add GHLToken table for OAuth tokens

Revision ID: fd180a5b7169
Revises: f8a5c2b3d4e6
Create Date: 2026-02-04 01:08:27.330305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd180a5b7169'
down_revision = 'f8a5c2b3d4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ghl_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('app_user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ghl_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ghl_tokens_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ghl_tokens_location_id'), ['location_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ghl_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ghl_tokens_location_id'))
        batch_op.drop_index(batch_op.f('ix_ghl_tokens_company_id'))

    op.drop_table('ghl_tokens')
    # ### end Alembic commands ###
